cask_args appdir: '/Applications'

tap 'jesseduffield/lazygit'
tap 'FelixKratz/formulae'
tap 'koekeishiya/formulae'
tap 'd12frosted/emacs-plus'

brew 'cloudflared'
brew 'wget'
brew 'neovim'
brew 'starship'
brew 'zellij'
brew 'ollama'
brew 'gh'
brew 'bat'
brew 'zoxide'
brew 'eza'
brew 'fd'
brew 'ripgrep'
brew 'fzf'
brew 'direnv'
brew 'lazygit'
brew 'lazydocker'
brew 'jq'
brew 'sketchybar'
brew 'tmux'
brew 'btop'
brew 'koekeishiya/formulae/yabai'
brew 'koekeishiya/formulae/skhd'
brew 'ranger'
brew 'yazi'
brew 'd12frosted/emacs-plus/emacs-plus@29'

cask '1password'
cask 'alacritty'
cask 'notion-calendar'
cask 'notion'
cask 'font-monaspice-nerd-font'
cask 'font-symbols-only-nerd-font' # nerd-icons glyphs (doom modeline/dashboard)
cask 'raycast'
cask 'vlc'
cask 'eqmac'
cask 'arc'
cask 'zed'
cask 'sf-symbols'
cask 'kitty'
