cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'sst/tap'
tap 'jesseduffield/lazygit'
tap 'FelixKratz/formulae'

brew 'cloudflared'
brew 'imagemagick'
brew 'spaceman-diff'
brew 'wget'
brew 'neovim'
brew 'starship'
brew 'zellij'
brew 'htop'
brew 'ollama'
brew 'gh'
brew 'helix'
brew 'bat'
brew 'zoxide'
brew 'eza'
brew 'fd'
brew 'ripgrep'
brew 'fzf'
brew 'sst'
brew 'lazygit'
brew 'jq'
brew 'sketchybar'
brew 'go'

cask '1password'
cask 'alacritty'
cask 'notion-calendar'
cask 'notion'
cask 'font-monaspace-nerd-font'
cask 'raycast'
cask 'visual-studio-code'
cask 'vlc'
cask 'eqmac'
cask 'arc'
cask 'sf-symbols'
